// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DevHabit.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class CatchingUpWithMilan : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_tags_name",
                schema: "dev_habit",
                table: "tags");

            migrationBuilder.AddColumn<string>(
                name: "user_id",
                schema: "dev_habit",
                table: "tags",
                type: "character varying(500)",
                maxLength: 500,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "user_id",
                schema: "dev_habit",
                table: "habits",
                type: "character varying(500)",
                maxLength: 500,
                nullable: false,
                defaultValue: "");

            migrationBuilder.CreateTable(
                name: "git_hub_access_tokens",
                schema: "dev_habit",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    user_id = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    token = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: false),
                    expires_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_git_hub_access_tokens", x => x.id);
                    table.ForeignKey(
                        name: "fk_git_hub_access_tokens_users_user_id",
                        column: x => x.user_id,
                        principalSchema: "dev_habit",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_tags_user_id_name",
                schema: "dev_habit",
                table: "tags",
                columns: new[] { "user_id", "name" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_habits_user_id",
                schema: "dev_habit",
                table: "habits",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ix_git_hub_access_tokens_user_id",
                schema: "dev_habit",
                table: "git_hub_access_tokens",
                column: "user_id",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "fk_habits_users_user_id",
                schema: "dev_habit",
                table: "habits",
                column: "user_id",
                principalSchema: "dev_habit",
                principalTable: "users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_tags_users_user_id",
                schema: "dev_habit",
                table: "tags",
                column: "user_id",
                principalSchema: "dev_habit",
                principalTable: "users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_habits_users_user_id",
                schema: "dev_habit",
                table: "habits");

            migrationBuilder.DropForeignKey(
                name: "fk_tags_users_user_id",
                schema: "dev_habit",
                table: "tags");

            migrationBuilder.DropTable(
                name: "git_hub_access_tokens",
                schema: "dev_habit");

            migrationBuilder.DropIndex(
                name: "ix_tags_user_id_name",
                schema: "dev_habit",
                table: "tags");

            migrationBuilder.DropIndex(
                name: "ix_habits_user_id",
                schema: "dev_habit",
                table: "habits");

            migrationBuilder.DropColumn(
                name: "user_id",
                schema: "dev_habit",
                table: "tags");

            migrationBuilder.DropColumn(
                name: "user_id",
                schema: "dev_habit",
                table: "habits");

            migrationBuilder.CreateIndex(
                name: "ix_tags_name",
                schema: "dev_habit",
                table: "tags",
                column: "name",
                unique: true);
        }
    }
}
